---
title: "PROJEKT NA ZAJĘCIA NR 4: Narracja"
author: "mmcharchuta"
date: "2025-04-29"
output:
  pdf_document: default
  html_document: default
always_allow_html: true
---
### PROJEKT NA ZAJĘCIA NR 4: Narracja
Przygotuj narrację prezentującą dowolne dane

WYMOGI:
- Prezentację narracji można przygotować ja w MS Wordzie lub innym programie, o ile zawiera wszystkie wymagane elementy.
- Narracja ma zaczynać się od tytułu i być podzielona na trzy części, każda wykorzystująca inny wzorzec prezentacji danych.
- Każda część musi składać się z 1 lub kilku paneli prezentujących dane wizualnie wraz z opisem słownym wymaganym do zrozumienia narracji.
- Dodatkowo każda część ma zawierać krótki opis odpowiadający na pytanie 'Co ma zrozumieć widz (ew. Na co ma zwrócić uwagę)?' 
  - Odpowiedź na to pytanie ma wykazać jak narracja ma być przekazana widzowi, np.: 'widz ma zapamiętać, że różnica pomiędzy X a Y jest większa niż gdziekolwiek indziej, co jest konieczne do zrozumienia aspektu Z narracji'.
- Do prezentacji musi być dostarczony kod w programie R umożliwiający generowanie tej prezentacji (wraz z importem wszystkich wymaganych bibliotek).


```{r project_Prezentacja_modułowa, message=FALSE, warning=FALSE}

``` 